from __future__ import annotations

from typing import Protocol, Sequence

from .models import AuditEvent, AuditReport, DecisionTrace


class AuditStorage(Protocol):
    def append_event(self, event: AuditEvent) -> None: ...
    def events_for_decision(self, decision_id: str) -> Sequence[AuditEvent]: ...
    def save_trace(self, trace: DecisionTrace) -> None: ...
    def get_trace(self, decision_id: str) -> DecisionTrace | None: ...
    def save_report(self, report: AuditReport) -> None: ...
    def get_report(self, decision_id: str) -> AuditReport | None: ...
