from __future__ import annotations

from typing import Protocol, Sequence

from .models import EvidenceItem, KnowledgeNode, KnowledgeRelationship, RetrievalQuery, RetrievalResult


class KnowledgeStore(Protocol):
    def all_nodes(self) -> Sequence[KnowledgeNode]: ...
    def all_relationships(self) -> Sequence[KnowledgeRelationship]: ...
    def all_evidence(self) -> Sequence[EvidenceItem]: ...
    def get_node(self, node_id: str) -> KnowledgeNode | None: ...
    def find_node_by_name(self, name: str) -> KnowledgeNode | None: ...
    def relationships_for_node(self, node_id: str) -> Sequence[KnowledgeRelationship]: ...
    def evidence_for_node(self, node_id: str) -> Sequence[EvidenceItem]: ...
    def evidence_for_relationship(self, relationship_id: str) -> Sequence[EvidenceItem]: ...


class EntityExpansionProvider(Protocol):
    def expand_entity(self, entity: str) -> Sequence[str]: ...


class SemanticSearchProvider(Protocol):
    def search(self, query: RetrievalQuery, entities: Sequence[str]) -> Sequence[RetrievalResult]: ...


class GraphSearchProvider(Protocol):
    def search(self, entities: Sequence[str], max_depth: int) -> Sequence[RetrievalResult]: ...
    def related(self, node_id: str, max_depth: int = 1) -> Sequence[KnowledgeNode]: ...
    def subgraph(self, node_id: str, max_depth: int = 1) -> tuple[Sequence[KnowledgeNode], Sequence[KnowledgeRelationship]]: ...


class EvidenceProvider(Protocol):
    def collect(self, node_ids: Sequence[str], relationship_ids: Sequence[str] = ()) -> Sequence[EvidenceItem]: ...


class ResultRanker(Protocol):
    def rank(self, results: Sequence[RetrievalResult]) -> Sequence[RetrievalResult]: ...


class ResultFilter(Protocol):
    def filter(self, results: Sequence[RetrievalResult], query: RetrievalQuery) -> Sequence[RetrievalResult]: ...
